# Generated by Django 3.0.8 on 2022-07-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='place_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
