# Generated by Django 3.0.8 on 2022-07-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='visit_flag',
        ),
        migrations.AlterField(
            model_name='comment',
            name='place_img',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁'), ('밤', '밤')], max_length=10),
        ),
    ]
