# Generated by Django 3.0.8 on 2022-07-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.TextField(choices=[('신촌동', '신촌동'), ('창천동', '창천동'), ('연희동', '연희동'), ('대현동', '대현동'), ('대신동', '대신동'), ('연남동', '연남동'), ('서교동', '서교동'), ('동교동', '동교동'), ('합정동', '합정동'), ('망원동', '망원동'), ('상수동', '상수동')]),
        ),
    ]
