# Generated by Django 3.0.8 on 2022-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='place_img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
