# Generated by Django 3.0.8 on 2022-07-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selected_flag',
            field=models.BooleanField(default=False),
        ),
    ]
