# Generated by Django 3.0.8 on 2022-07-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20220723_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='place_img',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
