# Generated by Django 3.0.8 on 2022-07-08 08:09

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_fix_url_to_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': [django.db.models.functions.comparison.Cast('place_id', output_field=models.IntegerField())]},
        ),
        migrations.AlterField(
            model_name='comment',
            name='place_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='drink',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='member_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
