# Generated by Django 3.0.8 on 2022-07-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(choices=[('entw', 'ENTW')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kakao_id', models.TextField()),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('profile_img', models.URLField(blank=True)),
                ('level', models.PositiveIntegerField(choices=[(2, '황금 접시'), (3, '은접시'), (4, '유리접시'), (5, '종이접시')])),
                ('select_count', models.PositiveIntegerField(default=0)),
                ('refresh_token', models.TextField(blank=True)),
                ('mbti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Mbti')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
