# Generated by Django 3.0.8 on 2022-07-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
