# Generated by Django 3.0.8 on 2022-07-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbti',
            name='mbti_img',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.TextField(null=True),
        ),
    ]
