# Generated by Django 3.0.8 on 2022-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_fix_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
